### ISSUE TITLE
request for regex support

### ISSUE THREAD

**Issue by M-Ghasemi** [kolypto/py-mongosql#6]
regex or at least `like` is one of the mandatory operators for a query engine, and apparently currently none of them are supported by mongosql.
I agree that `like` is not one of the MongoDB operators, but since implementing `$regex` is not that easy, maybe adding the following line to the `MongoFilter._operators_scalar is not a bad idea.

```
'$like': lambda col, val, oval: col.like(val),
```
```
_operators_scalar = {
    '$eq':  lambda col, val, oval: col == val,
    '$ne':  lambda col, val, oval: col.is_distinct_from(val),  # (see comment below)
    '$lt':  lambda col, val, oval: col < val,
    # '...'
    '$like': lambda col, val, oval: col.like(val),
}
```

**Comment by kolypto** [comment]
Hi @M-Ghasemi ! Thank you for your interest in the project :) 

You can actually register a custom operator, like this:

```python
from mongosql.handlers import MongoFilter

MongoFilter.add_scalar_operator(
    '$search', 
    lambda col, val, oval: col.ilike(f'%{val}%')
)
```

It is quite on purpose that `$regexp` is not available: it can potentially be very slow. I intentionally left this out :)
